//exp5
// even odd code
//WAP whhether the entered character is vowel or not.(if/else)
//WAP TO REVERSE THE Digit.
// WAP whether a triangle is equilateral/ isosceles/ scalene;
//
#include<stdio.h>
#include<process.h>
#include<conio.h>
int main()
{
system("cls");
int a;
scanf("%d", &a);
if(a%2==0){
	printf("number is even.");
} else {

	printf("number is odd.");
}
getch();
return 0;
}